### PR TITLE
feat(app-hub): add support for custom db port

### PR DESCRIPTION
**Pull request by erikarenhill**

### CODE REVIEW

**Comment by varl** [comment]
#### Case 1: Local DHIS2 instance on port 8080 with an internal database on 5432 (standard d2 cluster setup)

Start up App Hub with Docker Compose I get:

```
varl@jessika:~/dev/dhis2/support/docker-compose/app-hub$ ./scripts/start-and-seed.sh
Creating network "app-hub_default" with the default driver
Creating app-hub_db_1 ... done
Creating app-hub_core_1 ... error

ERROR: for app-hub_core_1  Cannot start service core: driver failed programming external connectivity on endpoint app-hub_core_1 (70ec8129f1f4bb1574e70b8330c35350ae6b17813e64a39869af41003922aa18): Bind for 0.0.0.0:8080 failed: port is already allocated

ERROR: for core  Cannot start service core: driver failed programming external connectivity on endpoint app-hub_core_1 (70ec8129f1f4bb1574e70b8330c35350ae6b17813e64a39869af41003922aa18): Bind for 0.0.0.0:8080 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

Starting with `DHIS2_APPHUB_PORT` set to 8081 everything works:

```
varl@jessika:~/dev/dhis2/support/docker-compose/app-hub$ DHIS2_APPHUB_PORT=8081 ./scripts/start-and-seed.sh
app-hub_db_1 is up-to-date
Recreating app-hub_core_1 ... done
Attaching to app-hub_db_1, app-hub_core_1
```

#### Case 2: Local DHIS2 instance (d2 cluster) on 8080/5432, local postgres server on 5432 and app-hub on 8081/5432

As long as the `DHIS2_APPHUB_PORT` does not conflict with the exposed port of DHIS2 (8080 by default), everything works still:

```
varl@jessika:~/dev/dhis2/support/docker-compose/app-hub$ DHIS2_APPHUB_PORT=8081 ./scripts/start-and-seed.sh 
Creating network "app-hub_default" with the default driver
Creating app-hub_db_1 ... done
Creating app-hub_core_1 ... done
Waiting 10 sec for containers to start
Seeding database with mock-data
Starting app-hub_db_1 ... done

> @dhis2/app-hub@1.0.0 seed-db /usr/src/app
....
Seeding reviews
Seeding channels
Seeding media_type
Seeding media
Ran 6 seed files
```

Unless I am missing something I do not think we need this PR since the DB is running in an isolated network, so it is possible to run Postgres on bare metal on 5432, and then in each docker compose cluster on 5432. They never interact since we never attempt to bind the internal postgres servers to the host port of 5432.

The problem here is that we get a conflict between the exposed ports (bound to host ports), i.e. that DHIS2 uses 8080 by default and App Hub uses 8080 by default.

**Comment by erikarenhill** [comment]
@varl indeed you are right, it's me being confused. The port as is, is internal to the docker network so it does not matter if multiple containers use the same port on their network.

Your case1 however is not due to any changes in this PR but probably because you are running something else on port 8080 ?

**Comment by erikarenhill** [comment]
Basically the only thing we need is more docs of how to start with another port for the frontend/server

**Comment by varl** [comment]
> Your case1 however is not due to any changes in this PR but probably because you are running something else on port 8080 ?

That's correct. I suspected that **case 1** was a common scenario and the one that @HendrikThePendric encountered, that's why I included it. **Case 3** was intended as a full-monty example where I tried to block off as many ports on 5432 to reproduce the problem.

That `8080` is blocked in all cases is expected because we need to bind the container network to the host network on a port on the host, so they may conflict.

So the fix is to just set `DHIS2_APPHUB_PORT` to something other than `8080`, and this is already supported without this PR, so you are right that we only need more docs. :+1:

**Comment by HendrikThePendric** [comment]
> That's correct. I suspected that **case 1** was a common scenario and the one that @HendrikThePendric encountered, that's why I included it.

I hereby confirm your suspicion

**Pull request closed without merging**
